### ISSUE TITLE
Set is not working

### ISSUE THREAD

**Issue by arielscherman** [tailsu/Telerik.JustMock.EntityFramework#1]
When i do:
context.Entity.ToList()

It works ok and it return all the items from Entity.

But when i do:

context.Set<Entity>().ToList()

It returns nothing

**Comment by tailsu** [comment]
Ah, good catch! Thanks for the report!

I just pushed a fix for `DbContext.Set<T>()`. The non-generic `DbContext.Set(Type)` still needs work, though.

**Comment by tailsu** [comment]
Closing this one, non-generic Set() feature request placed in #2
